// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaginationRequest {
    /// The number of items to return. Must be between 1 and 100. Default is 10.
    #[prost(int32, optional, tag="1")]
    pub limit: ::core::option::Option<i32>,
    /// The cursor to start from. If not provided, starts from the beginning.
    #[prost(string, optional, tag="2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaginationResponse {
    /// The next cursor to use for the next page of results. If there are no more pages, this will be empty.
    #[prost(string, tag="1")]
    pub next_cursor: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
