// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveUserFromOrganisationRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
/// Request for getting organisation dashboard info
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrganisationDashboardRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
}
/// Response for organisation dashboard info
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetOrganisationDashboardResponse {
    #[prost(int32, tag="1")]
    pub total_roles: i32,
    #[prost(int32, tag="2")]
    pub total_permissions: i32,
    #[prost(int32, tag="3")]
    pub total_principals: i32,
    #[prost(int32, tag="4")]
    pub total_users: i32,
}
/// Request for getting principal usage stats
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPrincipalUsageStatsRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
}
/// Response for principal usage stats
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPrincipalUsageStatsResponse {
    #[prost(int32, tag="1")]
    pub current_count: i32,
    #[prost(int32, tag="2")]
    pub included_count: i32,
    #[prost(int32, tag="3")]
    pub usage_percentage: i32,
    #[prost(int32, tag="4")]
    pub overage: i32,
    #[prost(double, tag="5")]
    pub overage_rate: f64,
    #[prost(double, tag="6")]
    pub estimated_overage_cost: f64,
    #[prost(string, tag="7")]
    pub current_billing_period: ::prost::alloc::string::String,
    #[prost(int32, tag="8")]
    pub days_left_in_billing_period: i32,
}
/// Request for getting usage history
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsageHistoryRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    /// Optional days to look back, defaults to 30
    #[prost(int32, tag="2")]
    pub days: i32,
}
/// Response for usage history
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsageHistoryResponse {
    #[prost(message, repeated, tag="1")]
    pub history: ::prost::alloc::vec::Vec<get_usage_history_response::UsageDataPoint>,
}
/// Nested message and enum types in `GetUsageHistoryResponse`.
pub mod get_usage_history_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UsageDataPoint {
        #[prost(string, tag="1")]
        pub date: ::prost::alloc::string::String,
        #[prost(int32, tag="2")]
        pub count: i32,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Project {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProjectResponse {
    #[prost(message, optional, tag="1")]
    pub project: ::core::option::Option<Project>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProjectRequest {
    /// organisation_id is the id of the organisation
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    /// name is the name of the new project
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProjectRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub project_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProjectsForOrganisationRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationRequest>,
    #[prost(string, optional, tag="3")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProjectsForOrganisationResponse {
    #[prost(message, repeated, tag="1")]
    pub projects: ::prost::alloc::vec::Vec<Project>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationResponse>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProjectResponse {
    #[prost(message, optional, tag="1")]
    pub project: ::core::option::Option<Project>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteProjectRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub project_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub email: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Organisation {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub users: ::prost::alloc::vec::Vec<User>,
    #[prost(message, optional, tag="4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="5")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="6")]
    pub billing_customer: ::core::option::Option<BillingCustomer>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BillingCustomer {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub email: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrganisationRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// user_id is the user that created the organisation and will be added as an admin
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateOrganisationResponse {
    #[prost(message, optional, tag="1")]
    pub organisation: ::core::option::Option<Organisation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrganisationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetOrganisationResponse {
    #[prost(message, optional, tag="1")]
    pub organisation: ::core::option::Option<Organisation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateOrganisationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateOrganisationResponse {
    #[prost(message, optional, tag="1")]
    pub organisation: ::core::option::Option<Organisation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetUsersOrganisationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub email: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InviteUserToOrganisationRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub email: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUsersOrganisationRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateApiKeyRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    /// project_name is the name of the project that the api key should be created in
    #[prost(string, tag="2")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApiKey {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="5")]
    pub invalidated: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateApiKeyResponse {
    #[prost(message, optional, tag="1")]
    pub api_key: ::core::option::Option<ApiKey>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListApiKeysRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    /// project_name is the name of the project to list the api keys for
    #[prost(string, tag="2")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationRequest>,
    /// search is a search string to filter the API Keys by name.
    #[prost(string, optional, tag="4")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListApiKeysResponse {
    #[prost(message, repeated, tag="1")]
    pub api_keys: ::prost::alloc::vec::Vec<ApiKey>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationResponse>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvalidateApiKeyRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    /// project_name is the name of the project that the api key belongs to
    #[prost(string, tag="2")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
}
include!("permio.organisation.v1.tonic.rs");
// @@protoc_insertion_point(module)