// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTotalRolesAndPermissionsForOrganisationRequest {
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetTotalRolesAndPermissionsForOrganisationResponse {
    #[prost(int32, tag="1")]
    pub total_roles: i32,
    #[prost(int32, tag="2")]
    pub total_permissions: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRolesRequest {
    /// project_name is the name of the project that the roles belong to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationRequest>,
    /// search is a search string to filter the roles by name.
    #[prost(string, optional, tag="4")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPermissionsRequest {
    /// project_name is the name of the project that the permissions belong to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationRequest>,
    /// search is a search string to filter the permissions by name.
    #[prost(string, optional, tag="3")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPrincipalsRequest {
    /// project_name is the name of the project that the principals belong to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationRequest>,
    /// search is a search string to filter the principals by name.
    #[prost(string, optional, tag="3")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckPermissionRequest {
    /// project_name is the name of the project to check permissions in.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// PrincipalID is the unique identifier of the principal.
    #[prost(string, tag="2")]
    pub principal_id: ::prost::alloc::string::String,
    /// ResourceURIs is a list of URIs of the resources to check.
    #[prost(string, repeated, tag="3")]
    pub resource_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Permissions is a list of permission names that the principal should have.
    #[prost(string, repeated, tag="4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MissingPermissions {
    #[prost(string, tag="1")]
    pub resource_uri: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub missing_permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckPermissionResponse {
    /// passed is true if the principal has all of the specified permissions on the specified resources.
    #[prost(bool, tag="1")]
    pub passed: bool,
    /// missing_permissions is a list of resources and the permissions that the principal does not have on them.
    #[prost(message, repeated, tag="2")]
    pub missing_permissions: ::prost::alloc::vec::Vec<MissingPermissions>,
}
/// ListPrincipalsResponse is the response to the ListPrincipals request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPrincipalsResponse {
    #[prost(string, repeated, tag="1")]
    pub principals: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationResponse>,
}
/// GetAllAssignmentsForPrincipalRequest is the request to get all assignments for a principal.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllAssignmentsForPrincipalRequest {
    /// project_name is the name of the project that principal belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// PrincipalID is the unique identifier of the principal.
    #[prost(string, tag="2")]
    pub principal_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationRequest>,
}
/// GetAllAssignmentsForPrincipalResponse is the response to the GetAllAssignmentsForPrincipal request.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllAssignmentsForPrincipalResponse {
    /// Assignments is a list of assignments for the principal.
    #[prost(message, repeated, tag="1")]
    pub assignments: ::prost::alloc::vec::Vec<Assignment>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationResponse>,
}
/// an InheritedRole is a role that a principal has inherited.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InheritedRole {
    #[prost(message, optional, tag="1")]
    pub role: ::core::option::Option<Role>,
    #[prost(string, tag="2")]
    pub inherited_from: ::prost::alloc::string::String,
}
/// an InheritedPermission is a permission that a principal has inherited from a role.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InheritedPermission {
    #[prost(message, optional, tag="1")]
    pub permission: ::core::option::Option<Permission>,
    #[prost(string, tag="2")]
    pub inherited_from: ::prost::alloc::string::String,
}
/// an Assignment is a set of permissions and roles assigned to a principal on a resource.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Assignment {
    /// ResourceURI is the URI of the resource to which the principal is assigned permissions.
    #[prost(string, tag="2")]
    pub resource_uri: ::prost::alloc::string::String,
    /// Permissions is a list of permissions that the principal has.
    #[prost(message, repeated, tag="3")]
    pub permissions: ::prost::alloc::vec::Vec<Permission>,
    /// Roles is a list of roles that the principal has.
    #[prost(message, repeated, tag="4")]
    pub roles: ::prost::alloc::vec::Vec<Role>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserPermissionsAndRolesOnResourceResponse {
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// UserID is the unique identifier of the user.
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// ResourceURI is the URI of the resource to which the user is being assigned permissions.
    #[prost(string, tag="3")]
    pub resource_uri: ::prost::alloc::string::String,
    /// Permissions is a list of permission names that should be assigned to the user.
    #[prost(string, repeated, tag="4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Roles is a list of role IDs that should be assigned to the user.
    #[prost(string, repeated, tag="5")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserPermissionsAndRolesOnResourceRequest {
    /// project_name is the name of the project that the grant  will belong to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// UserID is the unique identifier of the user.
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// ResourceURI is the URI of the resource to which the user is being assigned permissions.
    #[prost(string, tag="3")]
    pub resource_uri: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GrantUserPermissionsAndRolesOnResourceRequest {
    /// project_name is the name of the project that the grant  will belong to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// UserID is the unique identifier of the user.
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// ResourceURI is the URI of the resource to which the user is being assigned permissions.
    #[prost(string, tag="3")]
    pub resource_uri: ::prost::alloc::string::String,
    /// Permissions is a list of permission names that should be assigned to the user.
    #[prost(string, repeated, tag="4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Roles is a list of role IDs that should be assigned to the user.
    #[prost(string, repeated, tag="5")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePermissionRequest {
    /// project_name is the name of the project that the permission will belong to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// Name is the name of the permission.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// Description is the description of the permission.
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
}
/// a Permission identifies an action that can be performed on a resource.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Permission {
    /// ID is the unique identifier of the permission.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// OrganisationID is the unique identifier of the organisation that owns the permission.
    #[prost(string, tag="2")]
    pub organisation_id: ::prost::alloc::string::String,
    /// Name is the name of the permission.
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    /// Description is the description of the permission.
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    /// project_name is the name of the project that the permission belongs to.
    #[prost(string, tag="5")]
    pub project_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPermissionRequest {
    /// project_name is the name of the project that the permission belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// name is the name of the permission.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePermissionRequest {
    /// project_name is the name of the project that the permission belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// name is the current name of the permission to update.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// new_name is the new name of the permission (optional, if not provided, name stays the same).
    #[prost(string, optional, tag="3")]
    pub new_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Description is the description of the permission.
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePermissionRequest {
    /// project_name is the name of the project that the permission belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// name is the name of the permission.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPermissionsResponse {
    #[prost(message, repeated, tag="1")]
    pub permissions: ::prost::alloc::vec::Vec<Permission>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationResponse>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRoleRequest {
    /// project_name is the name of the project that the role belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// Name is the name of the role.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// Description is the description of the role.
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    /// Permissions is a list of permission names that the role has.
    #[prost(string, repeated, tag="4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// a Role is a collection of permissions.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Role {
    /// ID is the unique identifier of the role.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// OrganisationID is the unique identifier of the organisation that owns the role.
    #[prost(string, tag="2")]
    pub organisation_id: ::prost::alloc::string::String,
    /// Name is the name of the role.
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    /// Description is the description of the role.
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    /// Permissions is a list of permissions that the role contains.
    #[prost(message, repeated, tag="5")]
    pub permissions: ::prost::alloc::vec::Vec<Permission>,
    /// project_name is the name of the project that the role belongs to.
    #[prost(string, tag="6")]
    pub project_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRoleRequest {
    /// project_name is the name of the project that the role belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// id is the unique identifier of the role.
    #[prost(string, tag="2")]
    pub id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateRoleRequest {
    /// project_name is the name of the project that the role belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// id is the unique identifier of the role.
    #[prost(string, tag="2")]
    pub id: ::prost::alloc::string::String,
    /// name is the name of the role.
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    /// Description is the description of the role.
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    /// Permissions is a list of permission names that the role has.
    #[prost(string, repeated, tag="5")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteRoleRequest {
    /// project_name is the name of the project that the role belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// id is the unique identifier of the role.
    #[prost(string, tag="2")]
    pub id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRolesResponse {
    #[prost(message, repeated, tag="1")]
    pub roles: ::prost::alloc::vec::Vec<Role>,
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::pagination::PaginationResponse>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeUserPermissionsAndRolesOnResourceRequest {
    /// project_name is the name of the project that grant belongs to.
    #[prost(string, tag="1")]
    pub project_name: ::prost::alloc::string::String,
    /// UserID is the unique identifier of the user.
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// ResourceURI is the URI of the resource from which the user's permissions should be revoked.
    #[prost(string, tag="3")]
    pub resource_uri: ::prost::alloc::string::String,
    /// Permissions is a list of permission names that should be revoked from the user.
    #[prost(string, repeated, tag="4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Roles is a list of role IDs that should be revoked from the user.
    #[prost(string, repeated, tag="5")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// PrincipalCountUpdatedEvent is an event that is published when the number of unique principals in an organisation is updated.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrincipalCountUpdatedEvent {
    /// OrganisationID is the unique identifier of the organisation that the principal count was updated for.
    #[prost(string, tag="1")]
    pub organisation_id: ::prost::alloc::string::String,
    /// UniquePrincipalCount is the new number of unique principals in the organisation.
    #[prost(int64, tag="2")]
    pub unique_principal_count: i64,
}
include!("permio.permissions.v1.tonic.rs");
// @@protoc_insertion_point(module)